# Generated by Django 2.0.1 on 2019-09-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_auto_20180316_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IsolatedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isolated_words.Category')),
            ],
        ),
        migrations.CreateModel(
            name='IsolatedWordSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AudioData')),
                ('isolated_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isolated_words.IsolatedWord')),
            ],
        ),
    ]
