LEVELSENTENCESPEECH_PREFIX = "level_sentence_speech"

LEVELSENTENCESPEECH_LIST_URL_NAME = LEVELSENTENCESPEECH_PREFIX + "_list"
LEVELSENTENCESPEECH_CONTRIBUTORS_URL_NAME = LEVELSENTENCESPEECH_PREFIX + "_contributors"
