# Generated by Django 2.0.1 on 2018-03-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aphasia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphasia.Level')),
            ],
        ),
        migrations.RenameField(
            model_name='levelsentencespeech',
            old_name='tale_sentence',
            new_name='level_sentence',
        ),
        migrations.RemoveField(
            model_name='levelsentence',
            name='level',
        ),
        migrations.RemoveField(
            model_name='levelsentence',
            name='place',
        ),
        migrations.RemoveField(
            model_name='levelsentence',
            name='text',
        ),
        migrations.AlterField(
            model_name='levelsentencespeech',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.AudioData'),
        ),
        migrations.AddField(
            model_name='levelsentence',
            name='level_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aphasia.LevelCategory'),
            preserve_default=False,
        ),
    ]
