# Generated by Django 2.0.1 on 2018-03-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aphasia', '0002_auto_20180316_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelsentence',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
