# Generated by Django 2.0.1 on 2018-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aphasia', '0003_levelsentence_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
