ISOLATED_WORD_SPEECH_PREFIX = "isolated_word_speech"

ISOLATED_WORD_SPEECH_LIST_URL_NAME = ISOLATED_WORD_SPEECH_PREFIX + "_list"
ISOLATED_WORD_SPEECH_CONTRIBUTORS_URL_NAME = ISOLATED_WORD_SPEECH_PREFIX + "_contributors"
