# Generated by Django 2.0.1 on 2018-03-16 23:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180226_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audiofile',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='audio-data'),
        ),
    ]
