
APHASIA_LEVELS_URL_NAME = "aphasia_levels_api"
APHASIA_LEVEL_CATEGORY_URL_NAME = "aphasia_level_category_api"
APHASIA_LEVEL_CATEGORY_SENTENCES_URL_NAME = "aphasia_level_category_sentences_api"
APHASIA_UPLOAD_LEVEL_SENTENCE_URL_NAME = "aphasia_upload_level_sentence"
APHASIA_WORDS_URL_NAME = "aphasia_words_url_name"

ISOLATED_WORDS_CATEGORY_URL_NAME = "isolated_words_categories"
ISOLATED_WORDS_WORDS_LIST_URL_NAME = "isolated_words_word_list"
ISOLATED_WORDS_UPLOAD_WORD_URL_NAME = "isolated_words_upload_word"
