# Generated by Django 2.0.1 on 2018-02-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20151120_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususerprofile',
            name='anonymous_picture',
            field=models.ImageField(blank=True, null=True, upload_to='anonymous_pictures'),
        ),
        migrations.AlterField(
            model_name='anonymoususerprofilehistory',
            name='anonymous_picture',
            field=models.ImageField(blank=True, null=True, upload_to='anonymous_pictures'),
        ),
    ]
