# Generated by Django 2.0.1 on 2019-10-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180226_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='accent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='pitch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
